---
- name: redhat | Enabling EPEL Repo
  yum:
    name: epel-release
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Avahi Packages
  yum:
    name: "{{ avahi_redhat_packages }}"
    state: present
  become: true
  when: ansible_distribution != "Fedora"
